version: 2

jobs:
  validate:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

        # Set up a cached virtualenv in which to install tox
      - restore_cache:
          name: Restore build dependency cache
          key: deps-venv-{{ .Branch }}-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          name: Save build dependency cache
          key: deps-venv-{{ .Branch }}-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Validate reachability
          command: |
            . venv/bin/activate
            ./validate comp/main
            ./validate kickstart/main
            ./validate pre/main
            ./validate test/main


workflows:
  version: 2
  validate:
    jobs:
      - validate
