summary: Build the arena

component: Arena

milestone: $SRYYYY Competition

description: >-
    Build an arena or two to have the game in

dependencies:
    - comp/arena/network
    - comp/arena/power
    - comp/arena/screens

