summary: Build the arenas

component: Arena

milestone: $SRYYYY Competition

description: >-
    Build some arenas for the games.

dependencies:
    - comp/arena/network
    - comp/arena/power
    - comp/arena/screens

